# Generated by Django 3.0.3 on 2020-02-16 23:14
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("snmp_community", models.CharField(max_length=20)),
            ],
            options={"abstract": False},
        )
    ]
