# Generated by Django 3.0.3 on 2020-02-16 23:16
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0002_device")]

    operations = [
        migrations.AddField(
            model_name="device",
            name="loopback_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        )
    ]
