# Generated by Django 3.0.3 on 2020-02-17 04:32
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0008_auto_20200217_0354")]

    operations = [
        migrations.CreateModel(
            name="ManagementAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
            ],
            options={"abstract": False},
        )
    ]
