# Generated by Django 3.0.3 on 2020-02-17 05:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("main", "0009_managementaddress")]

    operations = [
        migrations.AddField(
            model_name="device",
            name="domain",
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
